function [output] = schroederReverb( ...
  inputSignal, ...
  Fs, ...
  combDelayMatrix, ...
  combType, ...
  allPassDelayMatrix, ...
  delay ...
)
  signalSize = length(inputSignal);
  [numCombs channels] = size(combDelayMatrix);
  [numAllPass unusedVariable] = size(allPassDelayMatrix);

  filteredSignals = [];
  for i = 1 : numCombs
      switch combType
          case 'IIR'
              filterOutput = IIR( ...
                  inputSignal, ...
                  delay, ...
                  combDelayMatrix(i,1) ...
              );
          case 'FIR'
              filterOutput = FIR( ...
                  inputSignal, ...
                  delay, ...
                  combDelayMatrix(i,1) ...
              );
          otherwise
              error('Unknown filtertype');
      end

      filteredSignals = [filteredSignals filterOutput];
  end

  filterOutput = combineSignals(filteredSignals);
  
  for j = 1 : numAllPass
      c = allPassDelayMatrix(j, 1);
      filterOutput = allPass(filterOutput, c);
  end

  output = filterOutput;
end